# Generated by Django 2.1.5 on 2019-05-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190504_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_quatity',
            field=models.IntegerField(default=1),
        ),
    ]
